version: '3.3'

services:
  
  frontend:
    restart: always
    build: ./frontend
    ports:
      - 3000:3000    #справа порт в контейнере

  api:
    restart: always
    build: ./api
    ports:
      - 5555:5000
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    restart: always
    image: adminer
    ports:
      - 8888:8080
      #docker-compose up --build
volumes:
  mysql_data: